{% set version = '3.3-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tmap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tmap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tmap/tmap_{{ version }}.tar.gz
  sha256: 60e58eef0f8c723db855d59117ca9f9b5e3663ba34b5ca783dc889bf20285e04

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-abind
    - r-classint >=0.4_3
    - r-htmltools
    - r-htmlwidgets
    - r-leafem >=0.1
    - r-leaflet >=2.0.2
    - r-leafsync
    - r-rlang
    - r-sf >=0.9_7
    - r-stars >=0.5_0
    - r-tmaptools >=3.1
    - r-units >=0.6_1
    - r-viridislite
    - r-widgetframe
  run:
    - r-base
    - r-rcolorbrewer
    - r-abind
    - r-classint >=0.4_3
    - r-htmltools
    - r-htmlwidgets
    - r-leafem >=0.1
    - r-leaflet >=2.0.2
    - r-leafsync
    - r-rlang
    - r-sf >=0.9_7
    - r-stars >=0.5_0
    - r-tmaptools >=3.1
    - r-units >=0.6_1
    - r-viridislite
    - r-widgetframe

test:
  commands:
    - $R -e "library('tmap')"           # [not win]
    - "\"%R%\" -e \"library('tmap')\""  # [win]

about:
  home: https://github.com/r-tmap/tmap
  license: GPL-3.0-or-later
  summary: Thematic maps are geographical maps in which spatial data distributions are visualized.
    This package offers a flexible, layer-based, and easy to use approach to create
    thematic maps, such as choropleths and bubble maps.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tmap
# License: GPL-3
# Title: Thematic Maps
# Type: Package
# LazyLoad: yes
# Authors@R: c( person("Martijn", "Tennekes", email = "mtennekes@gmail.com", role = c("aut", "cre")), person("Jakub", "Nowosad", email = "nowosad.jakub@gmail.com", role = "ctb"), person("Joel", "Gombin", email = "joel.gombin@gmail.com", role = "ctb"), person("Sebastian", "Jeworutzki", email = "Sebastian.Jeworutzki@rub.de", role = "ctb"), person("Kent", "Russell", email = "kent.russell@timelyportfolio.com", role = "ctb"), person("Richard", "Zijdeman", email = "richard.zijdeman@iisg.nl", role = "ctb"), person("John", "Clouse", email = "johnaclouse@gmail.com", role = "ctb"), person("Robin", "Lovelace", email = "rob00x@gmail.com", role = "ctb"), person("Jannes", "Muenchow", email = "jannes.muenchow@uni-jena.de", role = "ctb") )
# Description: Thematic maps are geographical maps in which spatial data distributions are visualized. This package offers a flexible, layer-based, and easy to use approach to create thematic maps, such as choropleths and bubble maps.
# Version: 3.3-3
# Date: 2022-03-01
# Encoding: UTF-8
# Depends: R (>= 3.5.0), methods
# Imports: tmaptools (>= 3.1), sf (>= 0.9-7), stars (>= 0.5-0), units (>= 0.6-1), grid, RColorBrewer, viridisLite, classInt (>= 0.4-3), htmltools, htmlwidgets, widgetframe, leaflet (>= 2.0.2), leafsync, leafem (>= 0.1), stats, abind, rlang, utils
# Suggests: rmapshaper, rmarkdown, knitr, png, cartogram, osmdata, ggplot2, dplyr, tidyr, shiny, testthat, covr, av, gifski, s2
# URL: https://github.com/r-tmap/tmap
# BugReports: https://github.com/r-tmap/tmap/issues
# VignetteBuilder: knitr
# RoxygenNote: 7.1.2
# NeedsCompilation: no
# Packaged: 2022-03-01 19:24:54 UTC; mtes
# Author: Martijn Tennekes [aut, cre], Jakub Nowosad [ctb], Joel Gombin [ctb], Sebastian Jeworutzki [ctb], Kent Russell [ctb], Richard Zijdeman [ctb], John Clouse [ctb], Robin Lovelace [ctb], Jannes Muenchow [ctb]
# Maintainer: Martijn Tennekes <mtennekes@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-03-02 08:50:02 UTC
