{% set name = "rocrate" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rocrate-{{ version }}.tar.gz
  sha256: 1eba5e01596676b250ac88806d1356e014949657838d9625c5947b845cf15b4d

build:
  entry_points:
    - rocrate=rocrate.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - arcp ==0.2.1
    - galaxy2cwl
    - jinja2
    - python-dateutil
    - click

test:
  imports:
    - rocrate
  commands:
    - pip check
    - rocrate --help
  requires:
    - pip

about:
  home: https://github.com/ResearchObject/ro-crate-py/
  summary: RO-Crate metadata generator/parser
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgruening
