package:
  name: cellh5
  version: "20.11.2017"

source:
  url: https://github.com/CellH5/cellh5/archive/6997bbf21348bd8115357ad21a374155331da415.zip
  sha256: e1ac9af59de68483cb00ac782b74cb4b3214b45ec3d2fdacdd405144cfb86bbb

build:
  noarch: python
  script: "python -m pip install --no-deps --ignore-installed ."
  number: 0

requirements:
  build:
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
  host:
    - python  <3
    - pip
    - numpy
    - h5py
    - six
    - matplotlib
    - pyqt
    - qimage2ndarray
    - pandas
    - lxml
  run:
    - python  <3
    - six
    - h5py
    - matplotlib
    - pyqt
    - qimage2ndarray
    - pandas
    - numpy
    - lxml

test:
  imports:
    - cellh5

about:
  home: https://github.com/CellH5/cellh5
  license: LGPL
  license_family: LGPL
  license_file: LICENSE
  summary: 'CellH5 is an HDF5 data format for cell-based assays in high-throughput microscopy'

extra:
  recipe-maintainers:
    - bgruening
