{% set name = "pypdb" %}
{% set version = "1.200" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8434a216d477593f046f1a2dfc3036d67c7b8478da85a4258efc636586d08425

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - beautifulsoup4
    - matplotlib
    - python
    - xmltodict

test:
  imports:
    - pypdb

about:
  home: https://github.com/williamgilpin/pypdb
  license: MIT
  license_family: MIT
  summary: A Python wrapper for the RCSB Protein Data Bank (PDB) API
  doc_url: http://www.wgilpin.com/pypdb_docs/html/
  dev_url: https://github.com/williamgilpin/pypdb

extra:
  recipe-maintainers:
    - bgruening
