{% set name = "racc" %}
{% set version = "1.5.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 2f48a44974ebc6b724f763f546a57706bbbeff571b7e1cf7d50919db413e139d

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Racc is a LALR(1) parser generator.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/tenderlove/racc

extra:
  recipe-maintainers:
    - bgruening
    - sodre
