{% set name = "cylowess" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b44cde6b7c3d4c7d35fa7ab93d1e1609ea966490183735f12c352d858c43c2ce

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - cylowess

about:
  home: https://github.com/livingsocial/cylowess
  license: UNKNOWN
  license_family: OTHER
  summary: "Lowess Cython implementation"
  dev_url: https://github.com/livingsocial/cylowess

extra:
  recipe-maintainers:
    - bgruening
