{% set version = '3.2.1' %}
{% set name = 'libfuse' %}

package:
  name: {{ name }}
  version: {{ version|replace("-", "_") }}

source:
  fn: fuse-3.2.1.tar.gz
  url: https://github.com/libfuse/libfuse/archive/fuse-3.2.1.tar.gz
  sha256: 1d20f820407f8c961569b80145dcf23104f04fefc029c1ac60026c3e75942bf1

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    #- toolchain
    - meson
    - ninja
  run:


test:
  commands:
    - test -f ${PREFIX}/lib/libz.a  # [unix]
    - conda inspect linkages -p ${PREFIX} libfuse  # [linux]

about:
  home: https://github.com/libfuse/libfuse
  license: GPL-2
  summary: The reference implementation of the Linux FUSE (Filesystem in Userspace) interface
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
