{% set version = '2.4.2' %}
{% set name = 'cvmfs' %}

package:
  name: {{ name }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/cvmfs/cvmfs/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 02cf018f9e7b097c309193fa693c8b81972d18fdc34e142d9f8bc1ea9883ac04

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    #- toolchain
    - cmake
    - xattr
    - attrs
    - zlib 1.2.*
    - curl >=7.44.0,<8
    - sqlite 3.20.1
    - sparsehash
    - libuuid 1.0.3
    - libfuse
    - protobuf 3.5.0
  run:
    - zlib 1.2.*
    - curl >=7.44.0,<8
    - sqlite 3.20.1
    - sparsehash
    - libuuid 1.0.3
    - libfuse
    - protobuf 3.5.0

test:
  commands:
    - cvmfs_config

about:
  home: https://github.com/cvmfs/cvmfs
  license: BSD 3-clause
  summary: The CernVM-File System (CernVM-FS) provides a scalable, reliable and low- maintenance filesystem that can be mounted over http.
  license_family: BSD
  license_file: COPYING

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
